-- Avant AI Studio Supabase schema
-- Run this in Supabase SQL Editor.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  public_id text not null unique,
  name text not null,
  contact text not null,
  niche text not null,
  message text not null,
  language text not null default 'uk',
  page text,
  source text not null default 'website',
  status text not null default 'new' check (status in ('new', 'in_progress', 'closed', 'cancelled')),
  sheet_status text not null default 'pending',
  telegram_status text not null default 'pending',
  meta_json jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.integration_logs (
  id bigint generated by default as identity primary key,
  lead_id bigint references public.leads(id) on delete cascade,
  channel text not null,
  status text not null,
  message text,
  created_at timestamptz not null default now()
);

create index if not exists idx_leads_created_at on public.leads (created_at desc);
create index if not exists idx_leads_status on public.leads (status);

alter table public.leads enable row level security;
alter table public.integration_logs enable row level security;

-- The backend should use the Supabase service role key on the server only.
-- Do not expose the service role key in frontend code.
