create table if not exists public.smm_targets (
  id bigint generated by default as identity primary key,
  url text not null unique,
  normalized_url text not null,
  company_name text,
  business_type text,
  description text,
  telegram_contacts jsonb not null default '[]'::jsonb,
  emails jsonb not null default '[]'::jsonb,
  phones jsonb not null default '[]'::jsonb,
  socials jsonb not null default '{}'::jsonb,
  offer_summary text,
  message_uk text,
  analysis_status text not null default 'pending',
  send_enabled boolean not null default false,
  send_status text not null default 'not_sent',
  sent_count integer not null default 0,
  last_sent_at timestamptz,
  error_message text,
  meta_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.smm_send_logs (
  id bigint generated by default as identity primary key,
  target_id bigint references public.smm_targets(id) on delete cascade,
  channel text not null default 'telegram',
  contact text,
  status text not null,
  message text,
  error_message text,
  sent_by bigint,
  created_at timestamptz not null default now()
);

create index if not exists idx_smm_targets_created_at on public.smm_targets (created_at desc);
create index if not exists idx_smm_targets_analysis_status on public.smm_targets (analysis_status);
create index if not exists idx_smm_targets_send_enabled on public.smm_targets (send_enabled);
create index if not exists idx_smm_send_logs_target_id on public.smm_send_logs (target_id);
